---

- name: Include {{ ansible_distribution }} vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: Dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true

- name: Retrieve Docker GPG key
  apt_key:
    keyserver: "{{ docker_key_server }}"
    id: "{{ docker_key_id }}"

- name: Install Docker repository
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present

- name: Configure systemd unit file (1/3)
  file:
    dest: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - /etc/docker
    - /etc/systemd/system/docker.service.d

- name: Configure systemd unit file (2/3)
  file:
    dest: /etc/docker/daemon.json
    state: touch
    mode: 0644
    owner: root
    group: root

- name: Configure systemd unit file (3/3)
  copy:
    src: docker.service
    dest: /etc/systemd/system/docker.service.d/docker.service
    mode: 0644
    owner: root
    group: root
  notify:
    - daemon-reload
    - restart docker
