- block:
  - include_vars: ubuntu.yml

  - name: Install Docker (Ubuntu)
    include: 01_ubuntu_install.yml

  - name: Configure Docker (Ubuntu)
    include: 02_ubuntu_configure.yml
    when: docker_aufs
  when: ansible_distribution == "Ubuntu"

- block:
  - include_vars: centos.yml

  - name: Install Docker (CentOS)
    include: 01_centos_install.yml

  - name: Configure Docker (CentOS)
    include: 02_centos_configure.yml
    when: docker_direct_lvm
  when: ansible_distribution == "CentOS"
